twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        tabler:
            dir: ltr # see if it is present in symfony/easyadmin
            theme: dark 
            layout:  # blank boxed fluid 

when@test:
    twig:
        strict_variables: true
